# version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      # Nome do Container do APP
    container_name: nome_do_container_codeigniter
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    ports:
      - "8080:80"  # Alterar PORTA
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: mysql:5.7
    # Nome do Container BD
    container_name: nome_do_container_codeigniter_db
    restart: always
    environment:
      MYSQL_USER: gabigol
      MYSQL_PASSWORD: teste_admin
      MYSQL_DATABASE: nome_do_projeto_db
      MYSQL_ROOT_PASSWORD: rootpassword  # Senha do root (necessário para iniciar o MySQL)
    ports:
      - "3306:3306"  # Alterar Porta do MySQL
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
